In [ ]:
import numpy as np
import nibabel as nib


In [6]:
M = np.arange(27).reshape((3, 3, 3))
M_yzx = np.array([[[ 0,  9, 18],[ 3, 12, 21],[6, 15, 24]],
                  [[ 1, 10, 19],[ 4, 13, 22],[ 7, 16, 25]],
                  [[ 2, 11, 20],[ 5, 14, 23],[ 8, 17, 26]]])

M_xzy = np.array([[[ 0,  1,  2],[ 9,  10,  11],[ 18,  19,  20]],
                    [[ 3, 4, 6],[12, 13, 14],[21, 22, 23]],
                    [[6, 7, 8],[15, 16, 17],[24, 25, 26]]])

print("M", M)
print("M_yzx", M_yzx)
print("M_xzy", M_xzy)


M [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
M_yzx [[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]
M_xzy [[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  6]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


In [7]:
print("Original 3D matrix:")
print(M)

# Step 2: Transpose the axes
# M_xzy (not exactly what we want )
transposed_matrix = np.transpose(M, (1, 0, 2))
print("\nTransposed 3D matrix (axes 0 and 1 swapped):")
print(transposed_matrix)

# Transpose axes to change scan order in z-direction 
# THIS IS WHAT WE WANT (but need to check how volume is placed in the beginning)
# M_yzx
transposed_matrix_2 = np.transpose(M, (2, 1, 0))
print("\nTransposed 3D matrix (axes 0 and 2 swapped):")
print(transposed_matrix_2)

Original 3D matrix:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Transposed 3D matrix (axes 0 and 1 swapped):
[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]

Transposed 3D matrix (axes 0 and 2 swapped):
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [10]:
# Correct slicing: extracting xy-plane from the 3D matrix
M[0, :, :], M_yzx[0, :, :], M_xzy[0, :, :]

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]]),
 array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]))

In [11]:
# Extracting xz-plane from the 3D matrix
M[:, 0, :], M_yzx[:, 0, :], M_xzy[:, 0, :]

(array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]]),
 array([[0, 1, 2],
        [3, 4, 6],
        [6, 7, 8]]))