In [2]:
import os
import nibabel as nib
import numpy as np

def check_affine_matrices(parent_dir):
    # List of file suffixes to check
    files_to_check = [
        "_ChP_mask_FLAIR_manual_seg.nii",
        "_ChP_mask_T1_manual_seg.nii",
        "_ChP_mask_T1xFLAIR_manual_seg.nii",
        "_T1.nii",
        "_T1xFLAIR.nii"
    ]

    # Initialize dictionaries to store results and affine matrices
    results = {suffix: [] for suffix in files_to_check}
    affine_matrices = {suffix: {} for suffix in files_to_check}
    affine_matrices["_FLAIR.nii"] = {}


    # Iterate over the directories in the parent directory
    for subject_id in sorted(os.listdir(parent_dir)):
        subject_dir = os.path.join(parent_dir, subject_id)
        
        # Load the reference T1.nii file
        reference_file = os.path.join(subject_dir, f"{subject_id}_FLAIR.nii")
        if not os.path.isfile(reference_file):
            print(f"Reference file {reference_file} not found for subject {subject_id}")
            continue
        

        reference_img = nib.load(reference_file)
        reference_affine = reference_img.affine
        # Add the reference affine matrix to the dictionary
        affine_matrices["_FLAIR.nii"][subject_id] = reference_affine
        
        # Check the affine matrices of the other files
        for file_suffix in sorted(files_to_check):
            file_to_check = os.path.join(subject_dir, f"{subject_id}{file_suffix}")
            print(f"Checking subject {subject_id}")
            print(reference_file, "---", file_to_check)
            if not os.path.isfile(file_to_check):
                print(f"File {file_to_check} not found for subject {subject_id}")
                continue
            
            img_to_check = nib.load(file_to_check)
            affine_to_check = img_to_check.affine

            affine_matrices[file_suffix][subject_id] = affine_to_check
            
            
            if np.allclose(reference_affine, affine_to_check):
                results[file_suffix].append((subject_id, "check"))
            else:
                results[file_suffix].append((subject_id, "matrices are not equal"))

    # Print the results sorted by subject identifier
    for file_suffix, result_list in results.items():
        print(f"Results for {file_suffix}:")
        for subject_id, status in sorted(result_list):
            print(f"{subject_id}: {status}")
            #print(f"Affine matrix:\n{affine_matrices[file_suffix][subject_id]}")

    return results, affine_matrices


# Example usage
parent_directory = '/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests'
results, affine_matrices = check_affine_matrices(parent_directory)

Checking subject 001
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_FLAIR.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_ChP_mask_FLAIR_manual_seg.nii
Checking subject 001
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_FLAIR.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_ChP_mask_T1_manual_seg.nii
Checking subject 001
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_FLAIR.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_ChP_mask_T1xFLAIR_manual_seg.nii
Checking subject 001
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_FLAIR.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_T1.nii
Checking subject 001
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_FLAIR.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/001/001_T1xFLAIR.nii
Checking subject 002
/home/linuxlia/Lia_Masterthesis/da

In [2]:
sorted(results['_ChP_mask_FLAIR_manual_seg.nii'])

[('001', 'check'),
 ('002', 'check'),
 ('003', 'check'),
 ('004', 'check'),
 ('005', 'matrices are not equal'),
 ('006', 'check'),
 ('007', 'check'),
 ('008', 'check'),
 ('009', 'check'),
 ('010', 'check'),
 ('011', 'check'),
 ('012', 'check'),
 ('013', 'check'),
 ('014', 'check'),
 ('015', 'check'),
 ('016', 'check'),
 ('017', 'check'),
 ('018', 'check'),
 ('019', 'check'),
 ('020', 'check'),
 ('021', 'check'),
 ('022', 'check'),
 ('023', 'check'),
 ('024', 'check'),
 ('025', 'check'),
 ('026', 'matrices are not equal'),
 ('027', 'check'),
 ('028', 'check'),
 ('029', 'check'),
 ('030', 'check'),
 ('031', 'check'),
 ('032', 'check'),
 ('033', 'check'),
 ('034', 'check'),
 ('035', 'check'),
 ('036', 'check'),
 ('037', 'check'),
 ('038', 'check'),
 ('039', 'check'),
 ('040', 'check'),
 ('041', 'check'),
 ('042', 'check'),
 ('043', 'check'),
 ('044', 'check'),
 ('045', 'check'),
 ('046', 'check'),
 ('047', 'check'),
 ('048', 'check'),
 ('049', 'check'),
 ('050', 'check'),
 ('051', 'check'

In [60]:
sorted(results['_T1.nii'])

[('001', 'check'),
 ('002', 'check'),
 ('003', 'check'),
 ('004', 'check'),
 ('005', 'check'),
 ('006', 'check'),
 ('007', 'check'),
 ('008', 'check'),
 ('009', 'check'),
 ('010', 'check'),
 ('011', 'check'),
 ('012', 'check'),
 ('013', 'check'),
 ('014', 'check'),
 ('015', 'check'),
 ('016', 'check'),
 ('017', 'check'),
 ('018', 'check'),
 ('019', 'check'),
 ('020', 'check'),
 ('021', 'check'),
 ('022', 'check'),
 ('023', 'check'),
 ('024', 'check'),
 ('025', 'check'),
 ('026', 'check'),
 ('027', 'check'),
 ('028', 'check'),
 ('029', 'check'),
 ('030', 'check'),
 ('031', 'check'),
 ('032', 'check'),
 ('033', 'check'),
 ('034', 'check'),
 ('035', 'check'),
 ('036', 'check'),
 ('037', 'check'),
 ('038', 'check'),
 ('039', 'check'),
 ('040', 'check'),
 ('041', 'check'),
 ('042', 'check'),
 ('043', 'check'),
 ('044', 'check'),
 ('045', 'check'),
 ('046', 'check'),
 ('047', 'check'),
 ('048', 'check'),
 ('049', 'check'),
 ('050', 'check'),
 ('051', 'check'),
 ('052', 'check'),
 ('053', 'ch

In [3]:
print(affine_matrices['_ChP_mask_T1_manual_seg.nii']['005']) 
print(affine_matrices['_T1.nii']['005']) 

[[ 9.97929573e-01 -1.55863129e-02 -6.23987801e-02 -8.86321945e+01]
 [ 5.31290472e-03  9.86852944e-01 -1.61533505e-01 -7.44450836e+01]
 [ 6.40961304e-02  1.60867557e-01  9.84892547e-01 -1.46268860e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.97939825e-01 -1.55863129e-02 -6.23987764e-02 -8.86321945e+01]
 [ 5.31296013e-03  9.86852944e-01 -1.61533505e-01 -7.44450836e+01]
 [ 6.40967861e-02  1.60867542e-01  9.84892547e-01 -1.46268860e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [4]:
np.allclose(affine_matrices['_T1.nii']['005'], affine_matrices['_ChP_mask_T1_manual_seg.nii']['005'])

False

In [5]:
rtol=1.e-5; atol=1.e-8
a = affine_matrices['_T1.nii']['005']
b = affine_matrices['_ChP_mask_T1_manual_seg.nii']['005']
np.absolute(a - b) <= (atol + rtol * np.absolute(b))

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
""" Read two files from subject (XXX_T1.nii and XXX_ChP_mask_T1xFLAIR_manual_seg.nii) read the affine matrices,
do the check of the individual elements of the matrices, if they are equal, continue with the next subject, if they are not equal,
 set the affine matrix of the XXX_ChP_mask_T1xFLAIR_manual_seg.nii to that of the XXX_T1.nii and overwrite the XXX_ChP_mask_T1xFLAIR_manual_seg.nii file
"""

def check_and_modify_affine_matrix(subject_id, parent_dir):
    # List of file suffixes to check
    files_to_check = [
        "_T1.nii",
        "_ChP_mask_T1_manual_seg.nii"
    ]

    # Initialize dictionaries to store results and affine matrices
    results = {suffix: [] for suffix in files_to_check}
    affine_matrices = {suffix: {} for suffix in files_to_check}
    
    # Iterate over the directories in the parent directory
    subject_dir = os.path.join(parent_dir, subject_id)
    
    # Load the reference T1.nii file
    reference_file = os.path.join(subject_dir, f"{subject_id}_T1.nii")
    if not os.path.isfile(reference_file):
        print(f"Reference file {reference_file} not found for subject {subject_id}")
        return
    
    reference_img = nib.load(reference_file)
    reference_affine = reference_img.affine
    # Add the reference affine matrix to the dictionary
    affine_matrices["_T1.nii"][subject_id] = reference_affine

    # Check the affine matrices of the other files
    for file_suffix in sorted(files_to_check):
        file_to_check = os.path.join(subject_dir, f"{subject_id}{file_suffix}")
        print(f"Checking subject {subject_id}")
        print(reference_file, "---", file_to_check)
        if not os.path.isfile(file_to_check):
            print(f"File {file_to_check} not found for subject {subject_id}")
            return

        img_to_check = nib.load(file_to_check)
        affine_to_check = img_to_check.affine

        affine_matrices[file_suffix][subject_id] = affine_to_check

        rtol=1.e-5; atol=1.e-8
        if np.allclose(reference_affine, affine_to_check, rtol=rtol, atol=atol):
            results[file_suffix].append((subject_id, "check"))
        else:
            results[file_suffix].append((subject_id, "matrices are not equal"))
            print(f"Affine matrix of {file_to_check} is different from {reference_file}")
            print(f"Setting the affine matrix of {file_to_check} to that of {reference_file}")
            # Create a new image with the updated affine matrix
            new_img = nib.Nifti1Image(img_to_check.get_fdata(), reference_affine, img_to_check.header)
            nib.save(new_img, file_to_check)
            
            print(f"Affine matrix of {file_to_check} is now equal to {  reference_file}")

check_and_modify_affine_matrix('099', parent_directory)


Checking subject 099
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_ChP_mask_T1_manual_seg.nii
Affine matrix of /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_ChP_mask_T1_manual_seg.nii is different from /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii
Setting the affine matrix of /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_ChP_mask_T1_manual_seg.nii to that of /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii
Affine matrix of /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_ChP_mask_T1_manual_seg.nii is now equal to /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii
Checking subject 099
/home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii --- /home/linuxlia/Lia_Masterthesis/data/pazienti_final_tests/099/099_T1.nii
